server:
  port: 9000
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      enable-auto-commit: true
      auto-commit-interval: 1000
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
